### ISSUE TITLE
Adopt Apache 2 license

### ISSUE THREAD

**Issue by jdolitsky** [chartmuseum/www#10]
We are working on migrating chartmuseum/ repos into the helm/ org. In order to do so, this repo must adopt the Apache 2 license.

Since this does not yet have a license, we need a unanimous "Yes" response from all of the contributors. Please comment "Yes" on this issue, or "No" with the reason.

Contributors:

- [x] @jdolitsky
- [x] @thiagosolcia
- [x] @karuppiah7890
- [x] @markrmullan
- [x] @scbizu

**Comment by markrmullan** [comment]
Yes

**Comment by scbizu** [comment]
Yes

**Comment by karuppiah7890** [comment]
Yes

**Comment by thiagosolcia** [comment]
Yes

**Comment by jdolitsky** [comment]
Thank you everyone!
