### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [chartmuseum/www#16]
Related: https://github.com/helm/helm-www/issues/1358

Notice from Netlify
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

As reported via deploy logs:
> DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
> 
> The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.
>
> To avoid service disruption, please select a newer build image at the following link:
https://app.netlify.com/sites/etcd/settings/deploys#build-image-selection
>
> For more details, visit the build image migration guide:
> https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by nate-double-u** [comment]
Friendly reminder that this website build image needs to be updated, builds will now fail if it isn't.

@bridgetkromhout, @mattfarina, @flynnduism -- I have you listed as admins in Netlify, can you confirm you have access?
(https://app.netlify.com/teams/helm/overview)

**Comment by flynnduism** [comment]
Thanks for the reminder @nate-double-u!

I've been able to login and update the image away from the deprecated prior default, for chartmuseum and all other sites under the Helm organization.

**Comment by nate-double-u** [comment]
Thanks @flynnduism!
Closing this issue as complete.
